spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/collection-record
    #url: jdbc:h2:mem:test
    username: sa
#    hikari:
#      jdbc-url: jdbc:h2:tcp://localhost/~/collection-record;MODE=MYSQL
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        storage_engine: innodb
